{% set name = "exdown" %}
{% set version = "0.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec65f8603d1dc56e6faee79665feb19c318e8c5429aadf394b65d4fa3f0209a7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - pytest

test:
  imports:
    - exdown
  requires:
    - pytest
  source_files:
    - test
  commands:
    - cd test && python -m pytest

about:
  home: https://github.com/nschloe/exdown
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Extract and test code blocks from Markdown

extra:
  recipe-maintainers:
    - nschloe
